### ISSUE TITLE
cannot find base_scene.xml

### ISSUE THREAD

**Issue by ErinZhang1998** [wagnew3/ARM#1]
Where can I get the `base_scene.xml` file that is used in `cluttered_scene_datagen.py`

**Comment by wagnew3** [comment]
apologies, added it at https://github.com/wagnew3/ARM/blob/master/inhand_datagen/base_scene.xml. You will also likely need the convex decompositions of shapenet objects, which are at https://drive.google.com/file/d/1AlA056SBR6xTmkrcnhE2ZJPKmhQv2z8P/view?usp=sharing

Let me know if you have any other questions, happy to help!
