### ISSUE TITLE
mujoco license problem

### ISSUE THREAD

**Issue by ErinZhang1998** [wagnew3/ARM#2]
I got a free temporary license from  https://www.roboti.us/license.html 
But somehow I am still getting the error `dm_control.mujoco.wrapper.core.Error: Could not register license.`
I have googled but didn't find a satisfactory answer, so I am wondering what kind of license you used for the project? And how did you use it?

Thanks!

**Comment by wagnew3** [comment]
Ah, I think the dm_control library looks for the license in a different place for some reason. I can't recall which, but I have the license at both .mujoco/mjkey.txt and .mujoco/mujoco200_linux/bin/mjkey.txt. Let me know if this helps!

**Comment by ErinZhang1998** [comment]
thank you!
