### ISSUE TITLE
Running the original GenRe code

### ISSUE THREAD

**Issue by ErinZhang1998** [wagnew3/ARM#3]
Hi I am wondering have you ever run the GenRe code, such as this one https://github.com/xiumingzhang/GenRe-ShapeHD, before using it for ARM? 
I can't run the code because of the error in `./build_toolbox.sh`; I understand that this is more of an issue for the GenRe people, but it seems very unlikely that they will reply, so it would super helpful if someone could help, since, from the paper, it seems like some code of ARM is based off from GenRe?

Thanks a lot!

**Comment by wagnew3** [comment]
Yes, this is an issue for ARM as well, that CUDA code needs to be installed for it to run. This is a tricky and frustrating error, basically there are some cpp pytorch bindings used that were depreciated in the move from pytorch 0.4 to 1.0. Have you successfully installed pytorch 0.4 as in the install instructions? I'm thinking about trying to rewrite these modules to be compatible with newer pytorch versions after the RSS deadline.

**Comment by ErinZhang1998** [comment]
Sadly, I cannot get the last line ` FULL_CAFFE2=1 NO_DISTRIBUTED=1 python setup.py install` to work in the installation for pytorch 0.4

Do we have to use Cuda 10, or can we use Cuda 9? Then I can maybe use `conda install pytorch=0.4.1 cuda90 -c pytorch`

**Comment by wagnew3** [comment]
I have installed this using CUDA 9. Installing pytorch 0.4 has unfortunately gotten harder and harder as other packages have been updated; you may also try to install other pytorch 0.4.x versions (available on their github). Let me know if you keep having issues!

**Comment by wagnew3** [comment]
I will try to rewrite the CUDA code after the neurips deadline to be compatible with modern pytorch versions.

**Comment by ErinZhang1998** [comment]
Thanks a lot!
