### ISSUE TITLE
Missing util directory?

### ISSUE THREAD

**Issue by ErinZhang1998** [wagnew3/ARM#4]
I was unable to run this line: https://github.com/wagnew3/ARM/blob/0e8750acc1ff5d5573e7aed1ce9be54ab7d58c9a/pose_model_estimator.py#L2 

Because of `ModuleNotFoundError: No module named 'util` 
Could you point me to the folder?

**Comment by wagnew3** [comment]
Apologies! I have pushed the utils folder, should work now.
